dependienteseconomicos:
    path:     /
    defaults: { _controller: "EstudioBundle:DependientesEconomicos:index" }

dependienteseconomicos_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:DependientesEconomicos:show" }

dependienteseconomicos_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:DependientesEconomicos:new" }

dependienteseconomicos_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:DependientesEconomicos:create" }
    methods:  POST

dependienteseconomicos_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:DependientesEconomicos:edit" }

dependienteseconomicos_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:DependientesEconomicos:update" }
    methods:  [POST, PUT]

dependienteseconomicos_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:DependientesEconomicos:delete" }
    methods:  [POST, DELETE]
