deudasactualesh5:
    path:     /
    defaults: { _controller: "EstudioBundle:DeudasActualesH5:index" }

deudasactualesh5_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:DeudasActualesH5:show" }

deudasactualesh5_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:DeudasActualesH5:new" }

deudasactualesh5_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:DeudasActualesH5:create" }
    methods:  POST

deudasactualesh5_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:DeudasActualesH5:edit" }

deudasactualesh5_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:DeudasActualesH5:update" }
    methods:  [POST, PUT]

deudasactualesh5_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:DeudasActualesH5:delete" }
    methods:  [POST, DELETE]
