esposahijos:
    path:     /
    defaults: { _controller: "EstudioBundle:EsposaHijos:index" }

esposahijos_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:EsposaHijos:show" }

esposahijos_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:EsposaHijos:new" }

esposahijos_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:EsposaHijos:create" }
    methods:  POST

esposahijos_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:EsposaHijos:edit" }

esposahijos_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:EsposaHijos:update" }
    methods:  [POST, PUT]

esposahijos_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:EsposaHijos:delete" }
    methods:  [POST, DELETE]
