pasatiempos:
    path:     /
    defaults: { _controller: "EstudioBundle:pasatiempos:index" }

pasatiempos_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:pasatiempos:show" }

pasatiempos_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:pasatiempos:new" }

pasatiempos_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:pasatiempos:create" }
    methods:  POST

pasatiempos_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:pasatiempos:edit" }

pasatiempos_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:pasatiempos:update" }
    methods:  [POST, PUT]

pasatiempos_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:pasatiempos:delete" }
    methods:  [POST, DELETE]
