hoja5_5:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja5_5:index" }

hoja5_5_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja5_5:show" }

hoja5_5_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja5_5:new" }

hoja5_5_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja5_5:create" }
    methods:  POST

hoja5_5_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja5_5:edit" }

hoja5_5_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja5_5:update" }
    methods:  [POST, PUT]

hoja5_5_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja5_5:delete" }
    methods:  [POST, DELETE]
