tarjetaCredito:
    path:     /
    defaults: { _controller: "EstudioBundle:tarjetaCredito:index" }

tarjetaCredito_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:tarjetaCredito:show" }

tarjetaCredito_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:tarjetaCredito:new" }

tarjetaCredito_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:tarjetaCredito:create" }
    methods:  POST

tarjetaCredito_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:tarjetaCredito:edit" }

tarjetaCredito_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:tarjetaCredito:update" }
    methods:  [POST, PUT]

tarjetaCredito_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:tarjetaCredito:delete" }
    methods:  [POST, DELETE]
