Imagenes_2:
    path:     /
    defaults: { _controller: "EstudioBundle:Imagenes_2:index" }

Imagenes_2_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Imagenes_2:show" }

Imagenes_2_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Imagenes_2:new" }

Imagenes_2_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Imagenes_2:create" }
    methods:  POST

Imagenes_2_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Imagenes_2:edit" }

Imagenes_2_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Imagenes_2:update" }
    methods:  [POST, PUT]

Imagenes_2_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Imagenes_2:delete" }
    methods:  [POST, DELETE]
