saludHigiene:
    path:     /
    defaults: { _controller: "EstudioBundle:saludHigiene:index" }

saludHigiene_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:saludHigiene:show" }

saludHigiene_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:saludHigiene:new" }

saludHigiene_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:saludHigiene:create" }
    methods:  POST

saludHigiene_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:saludHigiene:edit" }

saludHigiene_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:saludHigiene:update" }
    methods:  [POST, PUT]

saludHigiene_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:saludHigiene:delete" }
    methods:  [POST, DELETE]
