marcoFamiliar:
    path:     /
    defaults: { _controller: "EstudioBundle:marcoFamiliar:index" }

marcoFamiliar_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:marcoFamiliar:show" }

marcoFamiliar_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:marcoFamiliar:new" }

marcoFamiliar_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:marcoFamiliar:create" }
    methods:  POST

marcoFamiliar_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:marcoFamiliar:edit" }

marcoFamiliar_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:marcoFamiliar:update" }
    methods:  [POST, PUT]

marcoFamiliar_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:marcoFamiliar:delete" }
    methods:  [POST, DELETE]
