hoja3_2:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja3_2:index" }

hoja3_2_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja3_2:show" }

hoja3_2_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja3_2:new" }

hoja3_2_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja3_2:create" }
    methods:  POST

hoja3_2_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja3_2:edit" }

hoja3_2_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja3_2:update" }
    methods:  [POST, PUT]

hoja3_2_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja3_2:delete" }
    methods:  [POST, DELETE]
