hoja7_3:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja7_3:index" }

hoja7_3_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja7_3:show" }

hoja7_3_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja7_3:new" }

hoja7_3_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja7_3:create" }
    methods:  POST

hoja7_3_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja7_3:edit" }

hoja7_3_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja7_3:update" }
    methods:  [POST, PUT]

hoja7_3_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja7_3:delete" }
    methods:  [POST, DELETE]
