hoja7_2:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja7_2:index" }

hoja7_2_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja7_2:show" }

hoja7_2_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja7_2:new" }

hoja7_2_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja7_2:create" }
    methods:  POST

hoja7_2_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja7_2:edit" }

hoja7_2_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja7_2:update" }
    methods:  [POST, PUT]

hoja7_2_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja7_2:delete" }
    methods:  [POST, DELETE]
