MarcoFamiliar_4:
    path:     /
    defaults: { _controller: "EstudioBundle:MarcoFamiliar_4:index" }

MarcoFamiliar_4_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:MarcoFamiliar_4:show" }

MarcoFamiliar_4_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:MarcoFamiliar_4:new" }

MarcoFamiliar_4_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:MarcoFamiliar_4:create" }
    methods:  POST

MarcoFamiliar_4_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:MarcoFamiliar_4:edit" }

MarcoFamiliar_4_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:MarcoFamiliar_4:update" }
    methods:  [POST, PUT]

MarcoFamiliar_4_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:MarcoFamiliar_4:delete" }
    methods:  [POST, DELETE]
