hoja5_7:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja5_7:index" }

hoja5_7_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja5_7:show" }

hoja5_7_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja5_7:new" }

hoja5_7_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja5_7:create" }
    methods:  POST

hoja5_7_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja5_7:edit" }

hoja5_7_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja5_7:update" }
    methods:  [POST, PUT]

hoja5_7_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja5_7:delete" }
    methods:  [POST, DELETE]
