personasDomicilio:
    path:     /
    defaults: { _controller: "EstudioBundle:personasDomicilio:index" }

personasDomicilio_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:personasDomicilio:show" }

personasDomicilio_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:personasDomicilio:new" }

personasDomicilio_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:personasDomicilio:create" }
    methods:  POST

personasDomicilio_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:personasDomicilio:edit" }

personasDomicilio_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:personasDomicilio:update" }
    methods:  [POST, PUT]

personasDomicilio_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:personasDomicilio:delete" }
    methods:  [POST, DELETE]
