hoja4_1:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja4_1:index" }

hoja4_1_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja4_1:show" }

hoja4_1_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja4_1:new" }

hoja4_1_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja4_1:create" }
    methods:  POST

hoja4_1_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja4_1:edit" }

hoja4_1_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja4_1:update" }
    methods:  [POST, PUT]

hoja4_1_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja4_1:delete" }
    methods:  [POST, DELETE]
