egresos:
    path:     /
    defaults: { _controller: "EstudioBundle:egresos:index" }

egresos_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:egresos:show" }

egresos_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:egresos:new" }

egresos_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:egresos:create" }
    methods:  POST

egresos_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:egresos:edit" }

egresos_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:egresos:update" }
    methods:  [POST, PUT]

egresos_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:egresos:delete" }
    methods:  [POST, DELETE]
