referenciaFamiliar:
    path:     /
    defaults: { _controller: "EstudioBundle:referenciaFamiliar:index" }

referenciaFamiliar_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:referenciaFamiliar:show" }

referenciaFamiliar_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:referenciaFamiliar:new" }

referenciaFamiliar_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:referenciaFamiliar:create" }
    methods:  POST

referenciaFamiliar_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:referenciaFamiliar:edit" }

referenciaFamiliar_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:referenciaFamiliar:update" }
    methods:  [POST, PUT]

referenciaFamiliar_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:referenciaFamiliar:delete" }
    methods:  [POST, DELETE]
