hoja5_1:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja5_1:index" }

hoja5_1_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja5_1:show" }

hoja5_1_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja5_1:new" }

hoja5_1_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja5_1:create" }
    methods:  POST

hoja5_1_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja5_1:edit" }

hoja5_1_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja5_1:update" }
    methods:  [POST, PUT]

hoja5_1_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja5_1:delete" }
    methods:  [POST, DELETE]
