hoja5_6:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja5_6:index" }

hoja5_6_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja5_6:show" }

hoja5_6_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja5_6:new" }

hoja5_6_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja5_6:create" }
    methods:  POST

hoja5_6_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja5_6:edit" }

hoja5_6_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja5_6:update" }
    methods:  [POST, PUT]

hoja5_6_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja5_6:delete" }
    methods:  [POST, DELETE]
