hoja3:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja3:index" }

hoja3_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja3:show" }

hoja3_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja3:new" }

hoja3_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja3:create" }
    methods:  POST

hoja3_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja3:edit" }

hoja3_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja3:update" }
    methods:  [POST, PUT]

hoja3_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja3:delete" }
    methods:  [POST, DELETE]
