Imagenes_1:
    path:     /
    defaults: { _controller: "EstudioBundle:Imagenes_1:index" }

Imagenes_1_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Imagenes_1:show" }

Imagenes_1_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Imagenes_1:new" }

Imagenes_1_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Imagenes_1:create" }
    methods:  POST

Imagenes_1_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Imagenes_1:edit" }

Imagenes_1_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Imagenes_1:update" }
    methods:  [POST, PUT]

Imagenes_1_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Imagenes_1:delete" }
    methods:  [POST, DELETE]
