seguros:
    path:     /
    defaults: { _controller: "EstudioBundle:seguros:index" }

seguros_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:seguros:show" }

seguros_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:seguros:new" }

seguros_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:seguros:create" }
    methods:  POST

seguros_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:seguros:edit" }

seguros_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:seguros:update" }
    methods:  [POST, PUT]

seguros_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:seguros:delete" }
    methods:  [POST, DELETE]
