hoja6_1:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja6_1:index" }

hoja6_1_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja6_1:show" }

hoja6_1_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja6_1:new" }

hoja6_1_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja6_1:create" }
    methods:  POST

hoja6_1_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja6_1:edit" }

hoja6_1_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja6_1:update" }
    methods:  [POST, PUT]

hoja6_1_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja6_1:delete" }
    methods:  [POST, DELETE]
