hoja4:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja4:index" }

hoja4_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja4:show" }

hoja4_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja4:new" }

hoja4_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja4:create" }
    methods:  POST

hoja4_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja4:edit" }

hoja4_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja4:update" }
    methods:  [POST, PUT]

hoja4_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja4:delete" }
    methods:  [POST, DELETE]
