otrosServicios:
    path:     /
    defaults: { _controller: "EstudioBundle:otrosServicios:index" }

otrosServicios_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:otrosServicios:show" }

otrosServicios_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:otrosServicios:new" }

otrosServicios_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:otrosServicios:create" }
    methods:  POST

otrosServicios_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:otrosServicios:edit" }

otrosServicios_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:otrosServicios:update" }
    methods:  [POST, PUT]

otrosServicios_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:otrosServicios:delete" }
    methods:  [POST, DELETE]
