referenciasLaborales:
    path:     /
    defaults: { _controller: "EstudioBundle:referenciasLaborales:index" }

referenciasLaborales_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:referenciasLaborales:show" }

referenciasLaborales_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:referenciasLaborales:new" }

referenciasLaborales_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:referenciasLaborales:create" }
    methods:  POST

referenciasLaborales_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:referenciasLaborales:edit" }

referenciasLaborales_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:referenciasLaborales:update" }
    methods:  [POST, PUT]

referenciasLaborales_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:referenciasLaborales:delete" }
    methods:  [POST, DELETE]
