creditoAutomotriz:
    path:     /
    defaults: { _controller: "EstudioBundle:creditoAutomotriz:index" }

creditoAutomotriz_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:creditoAutomotriz:show" }

creditoAutomotriz_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:creditoAutomotriz:new" }

creditoAutomotriz_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:creditoAutomotriz:create" }
    methods:  POST

creditoAutomotriz_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:creditoAutomotriz:edit" }

creditoAutomotriz_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:creditoAutomotriz:update" }
    methods:  [POST, PUT]

creditoAutomotriz_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:creditoAutomotriz:delete" }
    methods:  [POST, DELETE]
