hoja8_1:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja8_1:index" }

hoja8_1_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja8_1:show" }

hoja8_1_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja8_1:new" }

hoja8_1_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja8_1:create" }
    methods:  POST

hoja8_1_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja8_1:edit" }

hoja8_1_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja8_1:update" }
    methods:  [POST, PUT]

hoja8_1_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja8_1:delete" }
    methods:  [POST, DELETE]
