ingresos:
    path:     /
    defaults: { _controller: "EstudioBundle:ingresos:index" }

ingresos_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:ingresos:show" }

ingresos_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:ingresos:new" }

ingresos_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:ingresos:create" }
    methods:  POST

ingresos_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:ingresos:edit" }

ingresos_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:ingresos:update" }
    methods:  [POST, PUT]

ingresos_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:ingresos:delete" }
    methods:  [POST, DELETE]
