creditosPersonales:
    path:     /
    defaults: { _controller: "EstudioBundle:creditosPersonales:index" }

creditosPersonales_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:creditosPersonales:show" }

creditosPersonales_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:creditosPersonales:new" }

creditosPersonales_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:creditosPersonales:create" }
    methods:  POST

creditosPersonales_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:creditosPersonales:edit" }

creditosPersonales_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:creditosPersonales:update" }
    methods:  [POST, PUT]

creditosPersonales_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:creditosPersonales:delete" }
    methods:  [POST, DELETE]
