referenciaVecinal:
    path:     /
    defaults: { _controller: "EstudioBundle:referenciaVecinal:index" }

referenciaVecinal_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:referenciaVecinal:show" }

referenciaVecinal_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:referenciaVecinal:new" }

referenciaVecinal_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:referenciaVecinal:create" }
    methods:  POST

referenciaVecinal_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:referenciaVecinal:edit" }

referenciaVecinal_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:referenciaVecinal:update" }
    methods:  [POST, PUT]

referenciaVecinal_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:referenciaVecinal:delete" }
    methods:  [POST, DELETE]
