hoja4_2:
    path:     /
    defaults: { _controller: "EstudioBundle:Hoja4_2:index" }

hoja4_2_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:Hoja4_2:show" }

hoja4_2_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:Hoja4_2:new" }

hoja4_2_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:Hoja4_2:create" }
    methods:  POST

hoja4_2_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:Hoja4_2:edit" }

hoja4_2_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:Hoja4_2:update" }
    methods:  [POST, PUT]

hoja4_2_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:Hoja4_2:delete" }
    methods:  [POST, DELETE]
