referenciapatroimonialautos:
    path:     /
    defaults: { _controller: "EstudioBundle:ReferenciaPatroimonialAutos:index" }

referenciapatroimonialautos_show:
    path:     /{id}/show
    defaults: { _controller: "EstudioBundle:ReferenciaPatroimonialAutos:show" }

referenciapatroimonialautos_new:
    path:     /new
    defaults: { _controller: "EstudioBundle:ReferenciaPatroimonialAutos:new" }

referenciapatroimonialautos_create:
    path:     /create
    defaults: { _controller: "EstudioBundle:ReferenciaPatroimonialAutos:create" }
    methods:  POST

referenciapatroimonialautos_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstudioBundle:ReferenciaPatroimonialAutos:edit" }

referenciapatroimonialautos_update:
    path:     /{id}/update
    defaults: { _controller: "EstudioBundle:ReferenciaPatroimonialAutos:update" }
    methods:  [POST, PUT]

referenciapatroimonialautos_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstudioBundle:ReferenciaPatroimonialAutos:delete" }
    methods:  [POST, DELETE]
