transport:
    path:     /
    defaults: { _controller: "UserBundle:transport:index" }

transport_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:transport:show" }

transport_new:
    path:     /new
    defaults: { _controller: "UserBundle:transport:new" }

transport_create:
    path:     /create
    defaults: { _controller: "UserBundle:transport:create" }
    methods:  POST

transport_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:transport:edit" }

transport_update:
    path:     /{id}/update
    defaults: { _controller: "UserBundle:transport:update" }
    methods:  [POST, PUT]

transport_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:transport:delete" }
    methods:  [POST, DELETE]
