users:
    path:     /
    defaults: { _controller: "UserBundle:users:index" }

users_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:users:show" }

users_new:
    path:     /new
    defaults: { _controller: "UserBundle:users:new" }

users_create:
    path:     /create
    defaults: { _controller: "UserBundle:users:create" }
    methods:  POST

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:users:edit" }

users_update:
    path:     /{id}/update
    defaults: { _controller: "UserBundle:users:update" }
    methods:  [POST, PUT]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:users:delete" }
    methods:  [POST, DELETE]
