HojaBundle\Entity\Hoja2:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        domicilio:
            type: string
            length: 255
            nullable: TRUE
        colonia:
            type: string
            length: '50'
            nullable: TRUE
        municipio:
            type: string
            length: '50'
            nullable: TRUE
        cp:
            type: integer
            nullable: TRUE
        entrecalle1:
            type: string
            length: '50'
            nullable: TRUE
        entrecalle2:
            type: string
            length: '50'
            nullable: TRUE
        ciudad:
            type: string
            length: '20'
            nullable: TRUE
        estado:
            type: string
            length: '20'
            nullable: TRUE
        antiguedadVivienda:
            type: integer
            nullable: TRUE
        antiguedadCiudad:
            type: integer
            nullable: TRUE
        telefonoLocal:
            type: integer
            nullable: TRUE
        celular:
            type: integer
            nullable: TRUE
        lugarNacimiento:
            type: string
            length: '50'
            nullable: TRUE
        fechaNacimiento:
            type: datetime
            nullable: TRUE
        nacionalidad:
            type: string
            length: '50'
            nullable: TRUE
        edad:
            type: integer
            nullable: TRUE
        estadoCivil:
            type: string
            length: '15'
            nullable: TRUE
        ocupacion:
            type: string
            length: '25'
            nullable: TRUE
        actaNacimiento:
            type: integer
            nullable: TRUE
        curp:
            type: string
            length: '25'
            nullable: TRUE
        actaMatrimonio:
            type: integer
            nullable: TRUE
        cartillaMilitar:
            type: integer
            nullable: TRUE
        comprobanteEstudios:
            type: string
            length: '30'
            nullable: TRUE
        licencia:
            type: integer
            nullable: TRUE
        comprobanteDomicilio:
            type: string
            length: '100'
            nullable: TRUE
        cartaRecomendacion1:
            type: string
            length: '100'
            nullable: TRUE
        cartaRecomendacion2:
            type: string
            length: '100'
            nullable: TRUE
        cartaRecomendacion3:
            type: string
            length: '100'
            nullable: TRUE
        credencialElector:
            type: integer
            nullable: TRUE
        seguroSocial:
            type: integer
            nullable: TRUE
        primaria:
            type: string
            length: 255
            nullable: TRUE
        de:
            type: date
            nullable: TRUE
        a:
            type: date
            nullable: TRUE
        comprobante:
            type: string
            length: '20'
            nullable: TRUE
        entidadPrimaria:
            type: string
            length: '100'
            nullable: TRUE
        secundaria:
            type: string
            length: 255
            nullable: TRUE
        deSecundaria:
            type: date
            nullable: TRUE
        aSecundaria:
            type: date
            nullable: TRUE
        comprobanteSecundaria:
            type: string
            length: '20'
            nullable: TRUE
        entidadSecundaria:
            type: string
            length: '100'
            nullable: TRUE
        preparatoria:
            type: string
            length: 255
            nullable: TRUE
        dePreparatoria:
            type: date
            nullable: TRUE
        aPreparatoria:
            type: date
            nullable: TRUE
        comprobantePreparatoria:
            type: string
            length: '20'
            nullable: TRUE
        entidadPreparatoria:
            type: string
            length: '100'
            nullable: TRUE
        profesional:
            type: string
            length: 255
            nullable: TRUE
        deProfesional:
            type: date
            nullable: TRUE
        aProfesional:
            type: date
            nullable: TRUE
        comprobanteProfesional:
            type: string
            length: '20'
            nullable: TRUE
        idiomas:
            type: string
            length: 255
            nullable: TRUE
        porcentajeHabla:
            type: integer
            nullable: TRUE
        porcentajeEscribe:
            type: integer
            nullable: TRUE
        porcentajeLee:
            type: integer
            nullable: TRUE
        observaciones:
            type: blob
            nullable: TRUE
    manyToOne:
        solicitud:         
            targetEntity: fourMinds\Bundle\ConfiguracionBundle\Entity\Solicitud
    lifecycleCallbacks: {  }