HojaBundle\Entity\Hoja7:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        observaciones:
            type: text
            nullable: TRUE
    manyToOne:
        solicitud:         
            targetEntity: fourMinds\Bundle\ConfiguracionBundle\Entity\Solicitud
    lifecycleCallbacks: {  }
