HojaBundle\Entity\MarcoFamiliar:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        observaciones:
            type: text
            nullable: TRUE
    manyToOne:
        solicitud:         
            targetEntity: fourMinds\Bundle\ConfiguracionBundle\Entity\Solicitud
    manyToMany:
      Familiares:
        targetEntity: EstudioBundle\Entity\Familiares
        joinTable:
          name: Familiares_investigado
          joinColumns:
            investigado_id:
              referencedColumnName: id
          inverseJoinColumns:
            familiares_id:
              referencedColumnName: id
        cascade: ["persist","remove"]
        onDelete: CASCADE
        options:
            cascade:
            remove: true
            persist: true 
      DependientesEconomicos:
        targetEntity: EstudioBundle\Entity\DependientesEconomicos
        joinTable:
          name: dependientesEconomicos_investigado
          joinColumns:
            investigado_id:
              referencedColumnName: id
          inverseJoinColumns:
            dependientesEconomicos_id:
              referencedColumnName: id
        cascade: ["persist","remove"]
        onDelete: CASCADE
        options:
            cascade:
            remove: true
            persist: true
      FamiliaresCercanos:
        targetEntity: EstudioBundle\Entity\FamiliaresCercanos
        joinTable:
          name: fCercanos_investigado
          joinColumns:
            investigado_id:
              referencedColumnName: id
          inverseJoinColumns:
            fCercanos_id:
              referencedColumnName: id
        cascade: ["persist","remove"]
        onDelete: CASCADE
        options:
            cascade:
            remove: true
            persist: true

    lifecycleCallbacks: {  }
