HojaBundle\Entity\Referencia_laboral:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        observaciones:
            type: text
            nullable: TRUE
    manyToOne:
        solicitud:         
            targetEntity: fourMinds\Bundle\ConfiguracionBundle\Entity\Solicitud
    manyToMany:      
      referenciasLaborales:
        targetEntity: EstudioBundle\Entity\referenciasLaborales
        joinTable:
          name: referenciasLaborales_investigado
          joinColumns:
            investigado_id:
              referencedColumnName: id
          inverseJoinColumns:
            dependientesEconomicos_id:
              referencedColumnName: id
        cascade: ["persist","remove"]
        onDelete: CASCADE
        options:
            cascade:
            remove: true
            persist: true
    lifecycleCallbacks: {  }
