configuracion:
    resource: "@ConfiguracionBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
estudio:
    resource: "@EstudioBundle/Resources/config/routing.yml"
    prefix:   /


