configuracion:
    resource: "@ConfiguracionBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /admin
login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
datos:
    resource: "@datosBundle/Resources/config/routing.yml"
    prefix:   /wipro
hoja:
    resource: "@HojaBundle/Resources/config/routing.yml"
    prefix:   /formato
Estudio:
    resource: "@EstudioBundle/Resources/config/routing.yml"
    prefix:   /es

