fourMinds\Bundle\UserBundle\Entity\perfil:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        telephone:
            type: string
            length: '14'
    manyToOne:
        file:         
            targetEntity: fourMinds\Bundle\UserBundle\Entity\file
            cascade: ["persist"]
    lifecycleCallbacks: {  }
