EstudioBundle\Entity\creditoAutomotriz:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        institucion:
            type: string
            length: '10'
            nullable: TRUE
        monto:
            type: float
            nullable: TRUE
        pagoMensual:
            type: float
            nullable: TRUE
        saldoActual:
            type: float
            nullable: TRUE
    lifecycleCallbacks: {  }
