EstudioBundle\Entity\creditosPersonales:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        institucion:
            type: string
            length: '10'
        montoCredito:
            type: float
        pagoMensual:
            type: float
        fonacot:
            type: string
            length: '10'
        montoFonacot:
            type: float
        pagoFonacot:
            type: float
        infonavit:
            type: string
            length: '10'
        montoInfonavit:
            type: float
        pagoInfonavit:
            type: float
        otros:
            type: string
            length: '10'
        montoOotros:
            type: float
        pagoOtros:
            type: float
    lifecycleCallbacks: {  }
