EstudioBundle\Entity\Hoja7_2:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
        tiempoConocer:
            type: string
            length: '20'
        domicilio:
            type: string
            length: '200'
        telefono:
            type: integer
        comentarios:
            type: text
    lifecycleCallbacks: {  }
