EstudioBundle\Entity\Hoja7_4:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        proyectos:
            type: text
        interesTrabajo:
            type: text
        trabajoSatisfactorio:
            type: text
        tiempoLibre:
            type: text
        musica:
            type: text
        lee:
            type: string
            length: '10'
        generoLectura:
            type: string
            length: '20'
        autorFavorito:
            type: string
            length: '50'
        asistenciaEventos:
            type: string
            length: '10'
        tipoEventos:
            type: string
            length: '100'
        asistenciaReuniones:
            type: string
            length: '10'
        tipoReuniones:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
