EstudioBundle\Entity\Hoja3_4:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        edad:
            type: integer
        parentesco:
            type: string
            length: '15'
        estadoCivil:
            type: string
            length: '15'
        escolaridad:
            type: string
            length: '80'
        ocupacion:
            type: string
            length: '20'
        salario:
            type: float
    lifecycleCallbacks: {  }