EstudioBundle\Entity\Hoja3_1:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        edad:
            type: integer
        parentesco:
            type: string
            length: '50'
        observaciones:
            type: text
    lifecycleCallbacks: {  }