EstudioBundle\Entity\imagen:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:        
        path:
            type: string
            length: '120'
            nullable:     true
        imagen:
            type: string
            length: '120'
            nullable:     true
        updated:       
            type:         datetime
            nullable:     true
    lifecycleCallbacks: 
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]
