EstudioBundle\Entity\ingresos:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        investigado:
            type: float
            nullable: TRUE
        conyuge:
            type: float
            nullable: TRUE
        padres:
            type: float
            nullable: TRUE
        hermanos:
            type: float
            nullable: TRUE
        otros:
            type: float
            nullable: TRUE
    lifecycleCallbacks: {  }
