EstudioBundle\Entity\otrosServicios:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cablemas:
            type: string
            length: '50'
            nullable: TRUE
        mastv:
            type: string
            length: '50'
            nullable: TRUE
        antenaParabolica:
            type: string
            length: '50'
            nullable: TRUE
        sky:
            type: string
            length: '50'
            nullable: TRUE
        otros:
            type: string
            length: '50'
            nullable: TRUE
        domestico:
            type: string
            length: '50'
            nullable: TRUE
        jardinero:
            type: string
            length: '50'
            nullable: TRUE
        chofer:
            type: string
            length: '50'
            nullable: TRUE
        vigilancia:
            type: string
            length: '50'
            nullable: TRUE
    lifecycleCallbacks: {  }
