EstudioBundle\Entity\PadresHermanos:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        edad:
            type: integer
        parentesco:
            type: string
            length: '15'
        estadoCivil:
            type: string
            length: '20'
        escolaridad:
            type: string
            length: '30'
        ocupacion:
            type: string
            length: '30'
    lifecycleCallbacks: {  }
