EstudioBundle\Entity\referenciaFamiliar:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
        parentesco:
            type: string
            length: '50'
        domicilio:
            type: string
            length: '100'
        telefono:
            type: integer
        comentarios:
            type: text
    lifecycleCallbacks: {  }
