EstudioBundle\Entity\ReferenciaPatroimonialAutos:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        marca:
            type: string
            length: 255
        modelo:
            type: string
            length: 255
        valorEstimado:
            type: float
        liquidado:
            type: boolean
    lifecycleCallbacks: {  }
