EstudioBundle\Entity\seguros:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        aseguradora:
            type: string
            length: '10'
            nullable: TRUE
        tipoSeguro:
            type: string
            length: '50'
            nullable: TRUE
        mensualidad:
            type: float
            nullable: TRUE
        vigencia:
            type: date
            nullable: TRUE
    lifecycleCallbacks: {  }
