EstudioBundle\Entity\seguros:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        aseguradora:
            type: string
            length: '10'
        tipoSeguro:
            type: string
            length: '50'
        mensualidad:
            type: float
        vigencia:
            type: date
    lifecycleCallbacks: {  }
