EstudioBundle\Entity\tarjetaCredito:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        banco:
            type: string
            length: '100'
            nullable: TRUE
        limiteCredito:
            type: float
            nullable: TRUE
        antiguedad:
            type: date
            nullable: TRUE
        pagoMensual:
            type: date
            nullable: TRUE
    lifecycleCallbacks: {  }
