<?php

namespace fourMinds\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * mensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mensajeRepository extends EntityRepository
{

    public function finByUser($id, $limit=0)
    {
        if($limit!=0){
            $limitqr=' limit '.$limit;
        }else{
            $limitqr='';
        }
        $dql = "select mensaje.id as msjid,`from_id`,`asunto`,`contenido`, mensaje.date_create, user.user_name,file
               from mensaje 
                inner join mensaje_user on mensaje.id=mensaje_user.user_id  
                inner join user on mensaje.from_id=user.id   
                inner join perfil on user.perfil_id =perfil.id
                inner join file on perfil.file_id=file.id            
                where mensaje_user.mensaje_id=".$id."  order by mensaje.date_create"; 
        $em = $this->getEntityManager();     
        $connection = $em->getConnection();
        $statement = $connection->prepare($dql);
        $statement->execute();
        $morosos = $statement->fetchAll();
        return $morosos;
    }

}
