
hoja4_show:
    path:     /{id}/show
    defaults: { _controller: "HojaBundle:Hoja4:show" }

hoja4:
    path:     /
    defaults: { _controller: "HojaBundle:Hoja4:new" }

hoja4_create:
    path:     /create
    defaults: { _controller: "HojaBundle:Hoja4:create" }
    methods:  POST

hoja4_edit:
    path:     /{id}/edit
    defaults: { _controller: "HojaBundle:Hoja4:edit" }

hoja4_update:
    path:     /{id}/update
    defaults: { _controller: "HojaBundle:Hoja4:update" }
    methods:  [POST, PUT]
hoja4_solicitud:
    path:     /{solicitud}/solicitud
    defaults: { _controller: "HojaBundle:Hoja4:showbysolicitud" }
hoja4_delete:
    path:     /{id}/delete
    defaults: { _controller: "HojaBundle:Hoja4:delete" }
    methods:  [POST, DELETE]
