
hoja5_show:
    path:     /{id}/show
    defaults: { _controller: "HojaBundle:Hoja5:show" }

hoja5:
    path:     /
    defaults: { _controller: "HojaBundle:Hoja5:new" }

hoja5_create:
    path:     /create
    defaults: { _controller: "HojaBundle:Hoja5:create" }
    methods:  POST

hoja5_edit:
    path:     /{id}/edit
    defaults: { _controller: "HojaBundle:Hoja5:edit" }

hoja5_update:
    path:     /{id}/update
    defaults: { _controller: "HojaBundle:Hoja5:update" }
    methods:  [POST, PUT]

hoja5_delete:
    path:     /{id}/delete
    defaults: { _controller: "HojaBundle:Hoja5:delete" }
    methods:  [POST, DELETE]
