
hoja8_show:
    path:     /{id}/show
    defaults: { _controller: "HojaBundle:Hoja8:show" }

hoja8:
    path:     /
    defaults: { _controller: "HojaBundle:Hoja8:new" }

hoja8_create:
    path:     /create
    defaults: { _controller: "HojaBundle:Hoja8:create" }
    methods:  POST

hoja8_edit:
    path:     /{id}/edit
    defaults: { _controller: "HojaBundle:Hoja8:edit" }

hoja8_update:
    path:     /{id}/update
    defaults: { _controller: "HojaBundle:Hoja8:update" }
    methods:  [POST, PUT]

hoja8_delete:
    path:     /{id}/delete
    defaults: { _controller: "HojaBundle:Hoja8:delete" }
    methods:  [POST, DELETE]
