
hoja6_show:
    path:     /{id}/show
    defaults: { _controller: "HojaBundle:Hoja6:show" }

hoja6:
    path:     /
    defaults: { _controller: "HojaBundle:Hoja6:new" }

hoja6_create:
    path:     /create
    defaults: { _controller: "HojaBundle:Hoja6:create" }
    methods:  POST

hoja6_edit:
    path:     /{id}/edit
    defaults: { _controller: "HojaBundle:Hoja6:edit" }

hoja6_update:
    path:     /{id}/update
    defaults: { _controller: "HojaBundle:Hoja6:update" }
    methods:  [POST, PUT]
hoja6_solicitud:
    path:     /{solicitud}/solicitud
    defaults: { _controller: "HojaBundle:Hoja6:showbysolicitud" }
hoja6_delete:
    path:     /{id}/delete
    defaults: { _controller: "HojaBundle:Hoja6:delete" }
    methods:  [POST, DELETE]
