
estudio_Bienes_autos:
    resource: "@EstudioBundle/Resources/config/routing/Bienes_autos.yml"
    prefix:   /Bienes_autos

estudio_Bienes_raices:
    resource: "@EstudioBundle/Resources/config/routing/Bienes_raices.yml"
    prefix:   /Bienes_raices


estudio_homepage:
    path:     /hello/{name}
    defaults: { _controller: EstudioBundle:Default:index }
