estudio_Hoja8_2:
    resource: "@EstudioBundle/Resources/config/routing/Hoja8_2.yml"
    prefix:   /Hoja8_2

estudio_hoja8_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja8_1.yml"
    prefix:   /hoja8_1

estudio_pasatiempos:
    resource: "@EstudioBundle/Resources/config/routing/pasatiempos.yml"
    prefix:   /pasatiempos

estudio_saludHigiene:
    resource: "@EstudioBundle/Resources/config/routing/saludHigiene.yml"
    prefix:   /saludHigiene

estudio_referenciaVecinal:
    resource: "@EstudioBundle/Resources/config/routing/referenciaVecinal.yml"
    prefix:   /referenciaVecinal

estudio_referenciaFamiliar:
    resource: "@EstudioBundle/Resources/config/routing/referenciaFamiliar.yml"
    prefix:   /referenciaFamiliar

estudio_referenciasLaborales:
    resource: "@EstudioBundle/Resources/config/routing/referenciasLaborales.yml"
    prefix:   /referenciasLaborales

estudio_otrosServicios:
    resource: "@EstudioBundle/Resources/config/routing/otrosServicios.yml"
    prefix:   /otrosServicios

estudio_creditoAutomotriz:
    resource: "@EstudioBundle/Resources/config/routing/creditoAutomotriz.yml"
    prefix:   /creditoAutomotriz

estudio_seguros:
    resource: "@EstudioBundle/Resources/config/routing/seguros.yml"
    prefix:   /seguros

estudio_creditosPersonales:
    resource: "@EstudioBundle/Resources/config/routing/creditosPersonales.yml"
    prefix:   /creditosPersonales

estudio_tarjetaCredito:
    resource: "@EstudioBundle/Resources/config/routing/tarjetaCredito.yml"
    prefix:   /tarjetaCredito

estudio_egresos:
    resource: "@EstudioBundle/Resources/config/routing/egresos.yml"
    prefix:   /egresos

estudio_ingresos:
    resource: "@EstudioBundle/Resources/config/routing/ingresos.yml"
    prefix:   /ingresos

estudio_hoja4_2:
    resource: "@EstudioBundle/Resources/config/routing/hoja4_2.yml"
    prefix:   /hoja4_2

estudio_hoja4_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja4_1.yml"
    prefix:   /hoja4_1

estudio_MarcoFamiliar_4:
    resource: "@EstudioBundle/Resources/config/routing/MarcoFamiliar_4.yml"
    prefix:   /MarcoFamiliar_4

estudio_marcoFamiliar:
    resource: "@EstudioBundle/Resources/config/routing/marcoFamiliar.yml"
    prefix:   /marcoFamiliar

estudio_personasDomicilio:
    resource: "@EstudioBundle/Resources/config/routing/personasDomicilio.yml"
    prefix:   /personasDomicilio

estudio_DependientesEconomicos:
    resource: "@EstudioBundle/Resources/config/routing/DependientesEconomicos.yml"
    prefix:   /DependientesEconomicos

estudio_homepage:
    path:     /hello/{name}
    defaults: { _controller: EstudioBundle:Default:index }
