estudio_hoja8_2:
    resource: "@EstudioBundle/Resources/config/routing/hoja8_2.yml"
    prefix:   /hoja8_2

estudio_hoja8_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja8_1.yml"
    prefix:   /hoja8_1

estudio_hoja7_4:
    resource: "@EstudioBundle/Resources/config/routing/hoja7_4.yml"
    prefix:   /hoja7_4

estudio_hoja7_3:
    resource: "@EstudioBundle/Resources/config/routing/hoja7_3.yml"
    prefix:   /hoja7_3

estudio_hoja7_2:
    resource: "@EstudioBundle/Resources/config/routing/hoja7_2.yml"
    prefix:   /hoja7_2

estudio_hoja7_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja7_1.yml"
    prefix:   /hoja7_1

estudio_hoja6_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja6_1.yml"
    prefix:   /hoja6_1

estudio_hoja5_7:
    resource: "@EstudioBundle/Resources/config/routing/hoja5_7.yml"
    prefix:   /hoja5_7

estudio_hoja5_5:
    resource: "@EstudioBundle/Resources/config/routing/hoja5_5.yml"
    prefix:   /hoja5_5

estudio_hoja5_6:
    resource: "@EstudioBundle/Resources/config/routing/hoja5_6.yml"
    prefix:   /hoja5_6

estudio_hoja5_4:
    resource: "@EstudioBundle/Resources/config/routing/hoja5_4.yml"
    prefix:   /hoja5_4

estudio_hoja5_3:
    resource: "@EstudioBundle/Resources/config/routing/hoja5_3.yml"
    prefix:   /hoja5_3

estudio_hoja5_2:
    resource: "@EstudioBundle/Resources/config/routing/hoja5_2.yml"
    prefix:   /hoja5_2

estudio_hoja5_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja5_1.yml"
    prefix:   /hoja5_1

estudio_hoja4_2:
    resource: "@EstudioBundle/Resources/config/routing/hoja4_2.yml"
    prefix:   /hoja4_2

estudio_hoja4_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja4_1.yml"
    prefix:   /hoja4_1

estudio_hoja3_4:
    resource: "@EstudioBundle/Resources/config/routing/hoja3_4.yml"
    prefix:   /hoja3_4

estudio_hoja3_3:
    resource: "@EstudioBundle/Resources/config/routing/hoja3_3.yml"
    prefix:   /hoja3_3

estudio_hoja3_2:
    resource: "@EstudioBundle/Resources/config/routing/hoja3_2.yml"
    prefix:   /hoja3_2

estudio_hoja3_1:
    resource: "@EstudioBundle/Resources/config/routing/hoja3_1.yml"
    prefix:   /hoja3_1

estudio_homepage:
    path:     /hello/{name}
    defaults: { _controller: EstudioBundle:Default:index }
