fourMinds\Bundle\ConfiguracionBundle\Entity\Cliente:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razonSocial:
            type: string
            length: '120'
    lifecycleCallbacks: {  }
