fourMinds\Bundle\ConfiguracionBundle\Entity\horasLaborales:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        inicio:
            type: time
        fin:
            type: time
    lifecycleCallbacks: {  }
