fourMinds\Bundle\ConfiguracionBundle\Entity\Solicitud:
    type: entity
    table: null
    repositoryClass: fourMinds\Bundle\ConfiguracionBundle\Entity\SolicitudRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        direccion:
            type: string
            length: 255
        telefonos:
            type: string
            length: 255
        puesto:
            type: string
            length: '120'
        formato:
            type: integer
        estatus:
            type: integer
        fecha:
            type: datetime
        fechaVisitador:
            type: datetime
        fechaRefencias:
            type: datetime
            nullable: true
        fechaFinal:
            type: datetime
        fechaTermino:
            type: datetime
            nullable: true
        fechaRefenciasTermino:
            type: datetime
            nullable: true
    manyToOne:
        cliente:         
            targetEntity: fourMinds\Bundle\ConfiguracionBundle\Entity\Cliente
        visitador:         
            targetEntity: fourMinds\Bundle\UserBundle\Entity\User
        capturista:         
            targetEntity: fourMinds\Bundle\UserBundle\Entity\User
        usuario_creo:         
            targetEntity: fourMinds\Bundle\UserBundle\Entity\User
    lifecycleCallbacks: {  }
