fourMinds\Bundle\ConfiguracionBundle\Entity\tiempoEtapa:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        etapa:
            type: integer
        tiempoVerde:
            type: integer
        tiempoAmarillo:
            type: integer
        tiempoRojo:
            type: integer
    lifecycleCallbacks: {  }
