fourMinds\Bundle\ConfiguracionBundle\Entity\tiempoEtapa:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        descripcion:
            type: string
            length: '120'       
        tiempoVerde:
            type: decimal
        tiempoAmarillo:
            type: decimal
        tiempoRojo:
            type: decimal
    lifecycleCallbacks: {  }
