alerts:
    path:     /
    defaults: { _controller: "UserBundle:alerts:index" }

alerts_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:alerts:show" }

alerts_new:
    path:     /new
    defaults: { _controller: "UserBundle:alerts:new" }

alerts_create:
    path:     /create
    defaults: { _controller: "UserBundle:alerts:create" }
    methods:  POST

alerts_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:alerts:edit" }

alerts_update:
    path:     /{id}/update
    defaults: { _controller: "UserBundle:alerts:update" }
    methods:  [POST, PUT]

alerts_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:alerts:delete" }
    methods:  [POST, DELETE]
