hoja_marcofamiliar:
    resource: "@HojaBundle/Resources/config/routing/marcofamiliar.yml"
    prefix:   /marcofamiliar

hoja_hoja9:
    resource: "@HojaBundle/Resources/config/routing/hoja9.yml"
    prefix:   /hoja9

hoja_hoja8:
    resource: "@HojaBundle/Resources/config/routing/hoja8.yml"
    prefix:   /hoja8

hoja_hoja7:
    resource: "@HojaBundle/Resources/config/routing/hoja7.yml"
    prefix:   /hoja7

hoja_hoja6:
    resource: "@HojaBundle/Resources/config/routing/hoja6.yml"
    prefix:   /hoja6

hoja_hoja5:
    resource: "@HojaBundle/Resources/config/routing/hoja5.yml"
    prefix:   /hoja5

hoja_hoja4:
    resource: "@HojaBundle/Resources/config/routing/hoja4.yml"
    prefix:   /hoja4
hoja_hoja2:
    resource: "@HojaBundle/Resources/config/routing/hoja2.yml"
    prefix:   /hoja2
hoja_hoja1:
    resource: "@HojaBundle/Resources/config/routing/hoja1.yml"
    prefix:   /hoja1
