hoja_marcofamiliar:
    resource: "@HojaBundle/Resources/config/routing/marcofamiliar.yml"
    prefix:   /marcofamiliar
    
hoja_Imagenes:
    resource: "@HojaBundle/Resources/config/routing/Imagenes.yml"
    prefix:   /Imagenes

hoja_Referencia_Personal:
    resource: "@HojaBundle/Resources/config/routing/Referencia_Personal.yml"
    prefix:   /Referencia_Personal

hoja_Referencia_laboral:
    resource: "@HojaBundle/Resources/config/routing/Referencia_laboral.yml"
    prefix:   /Referencia_laboral

hoja_Finanzas:
    resource: "@HojaBundle/Resources/config/routing/Finanzas.yml"
    prefix:   /Finanzas

hoja_Bienes:
    resource: "@HojaBundle/Resources/config/routing/Bienes.yml"
    prefix:   /Bienes
hoja_hoja2:
    resource: "@HojaBundle/Resources/config/routing/hoja2.yml"
    prefix:   /hoja2
hoja_hoja1:
    resource: "@HojaBundle/Resources/config/routing/hoja1.yml"
    prefix:   /hoja1
