<?php

namespace fourMinds\Bundle\ConfiguracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends EntityRepository
{

    public function tiempoFinal($horaSolicitud,$horaProceso,$horaEntrada,$horaSalida,$tiempoTotal=0)
    {
        $tiempoDia=24*60*60;
        $tiempo=$tiempoDia-$horaSalida;
        if($horaSolicitud > $horaEntrada && $horaSolicitud < $horaSalida)
        {            
            $tiempoTrabajo=$horaSalida-$horaSolicitud;                  
            if($tiempoTrabajo >$horaProceso )
            {
                $tiempoTotal=$tiempoTotal+$horaSolicitud+$horaProceso;
                //echo $tiempoTotal/(60*60).'|tiempoTotal<br>';
                //$fecha->add(new \DateInterval('PT'.$tiempoTotal.'S'));
                //session_start();
                $_SESSION['date']  =$tiempoTotal;
                //echo $fecha->format('Y-m-d H:i:s').'|result<br>';
                return $tiempoTotal;
            }else{                                
                $horaProceso=$horaProceso-$tiempoTrabajo;                
                $horaSolicitud=$horaEntrada+60;
                $tiempoTotal=$tiempoTrabajo+$tiempo;                
                $this->tiempoFinal($horaSolicitud,$horaProceso,$horaEntrada,$horaSalida,$tiempoTotal);
            }
        }else{
            $horaSolicitud=$horaEntrada+60;
            $this->tiempoFinal($horaSolicitud,$horaProceso,$horaEntrada,$horaSalida,0);
        }   
    }

}
